name: SpaceFarmer
favicon: null
layout_spectrum: 0.4139785
typography_spectrum: 0.651
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Hydroponics with 3d printing, oodles of sensors, and some home-brewed automation'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#5b5b5b'
    - '#a9018c'
    - '#0bfd57'
    - '#f76eee'
  brandStrength: 0.8261649
  lightness: 0.7301403607707471
  saturation: 0.9602152609732002
  rhythmicContrast: 0.5
purpose: []
